version: 2
updates:
  - package-ecosystem: gomod
    directories:
      - "/"
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "06:00"
    labels:
      - "theme/dependencies"
  