name: Admin - License Lint
on:
  push:
    paths-ignore:
      - '.github/workflows/**'
      - "build/**"
      - 'docs/**'
      - 'README.md'
jobs:
  copywrite:
    timeout-minutes: 1
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: hashicorp/setup-copywrite@32638da2d4e81d56a0764aa1547882fc4d209636 # v1.1.3
      - name: "Run Copywrite Verification"
        run: |
          copywrite --config build/license/copywrite.hcl headers --plan
