name: GitHub - Action Lint
on:
  push:
    paths:
      - '.github/workflows/**'
permissions:
  contents: read
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: raven-actions/actionlint@3a24062651993d40fed1019b58ac6fbdfbf276cc #v2.0.1
