name: Golang - Test
on:
  push:
    paths-ignore:
      - '.github/workflows/**'
      - 'docs/**'
      - 'README.md'
jobs:
  test:
    strategy:
      matrix:
        os: ["ubuntu-latest", "macos-latest"]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5 # v5.5.0
        with:
          go-version-file: 'go.mod'
      - name: "Run test"
        run: |
          make test-deps
          make test
