name: Golang - Compile

on:
  # The release workflow will call this workflow to build the binaries, so we
  # need to allow workflow triggers.
  workflow_call:
  push:
    paths-ignore:
      - '.github/workflows/**'
      - 'docs/**'
      - 'README.md'

jobs:
  compile:
    strategy:
      matrix:
        goos: ["darwin", "freebsd", "linux"]
        goarch: ["amd64", "arm64"]
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7.0.0
        with:
          go-version-file: "build/.go-version"
      - name: "Run compile"
        run: |
          make "bin/${{ matrix.goos }}_${{ matrix.goarch }}/attila"
      - uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: attila_${{ matrix.goos }}-${{ matrix.goarch }}
          path: bin/${{ matrix.goos }}_${{ matrix.goarch }}/attila
          retention-days: 14
